### ISSUE TITLE
Compilation error in the demo project

### ISSUE THREAD

**Issue by wbuchanan** [stefaneidelloth/javafx-d3#1]
First error I got was 

/Users/billy/Desktop/Programs/Java/javafx-d3/javafx-d3-demo/src/main/java/com/github/javafxd3/demo/client/democases/LorenzSystem.java:[81,58] unmappable character for encoding UTF8

It seemed like this was the unicode characters for the greek characters used in the equations that were commented out.  I deleted those commented out lines and then started getting a different compilation error.

lyndal-lmafic01:javafx-d3-demo billy$ mvn clean install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building javafx-d3-demo 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ javafx-d3-demo ---
[INFO] Deleting /Users/billy/Desktop/Programs/Java/javafx-d3/javafx-d3-demo/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ javafx-d3-demo ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 22 resources
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ javafx-d3-demo ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 35 source files to /Users/billy/Desktop/Programs/Java/javafx-d3/javafx-d3-demo/target/classes
[INFO] /Users/billy/Desktop/Programs/Java/javafx-d3/javafx-d3-demo/src/main/java/com/github/javafxd3/demo/client/democases/svg/brush/BrushTransitionsDemo.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/billy/Desktop/Programs/Java/javafx-d3/javafx-d3-demo/src/main/java/com/github/javafxd3/demo/client/democases/svg/brush/BrushTransitionsDemo.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/billy/Desktop/Programs/Java/javafx-d3/javafx-d3-demo/src/main/java/com/github/javafxd3/demo/client/democases/geom/ShapeTweeningDemo.java:[179,61] incompatible types: capture#1 of ? cannot be converted to double
[ERROR] /Users/billy/Desktop/Programs/Java/javafx-d3/javafx-d3-demo/src/main/java/com/github/javafxd3/demo/client/democases/geom/ShapeTweeningDemo.java:[180,62] incompatible types: capture#2 of ? cannot be converted to double
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.856 s
[INFO] Finished at: 2015-10-15T12:39:03-05:00
[INFO] Final Memory: 18M/349M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project javafx-d3-demo: Compilation failure: Compilation failure:
[ERROR] /Users/billy/Desktop/Programs/Java/javafx-d3/javafx-d3-demo/src/main/java/com/github/javafxd3/demo/client/democases/geom/ShapeTweeningDemo.java:[179,61] incompatible types: capture#1 of ? cannot be converted to double
[ERROR] /Users/billy/Desktop/Programs/Java/javafx-d3/javafx-d3-demo/src/main/java/com/github/javafxd3/demo/client/democases/geom/ShapeTweeningDemo.java:[180,62] incompatible types: capture#2 of ? cannot be converted to double
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
lyndal-lmafic01:javafx-d3-demo billy$

**Comment by stefaneidelloth** [comment]
Hi wbuchanan,
thank you for your feedback. I committed my current state and it might work now for you, too? I compile on windows 7 and my default encoding is different.Please skip the tests when compiling with maven. Those special characters from the gwt-d3 project are annoying and I'll do some bug hunting for them... 
Best regards,
Stefan

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building javafx-d3-demo 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ javafx-d3-demo ---
[INFO] Deleting D:\javafx-d3\javafx-d3-demo\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ javafx-d3-demo ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 25 resources
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ javafx-d3-demo ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 43 source files to D:\javafx-d3\javafx-d3-demo\target\classes
[INFO] /D:/javafx-d3/javafx-d3-demo/src/main/java/com/github/javafxd3/demo/client/democases/svg/brush/BrushTransitionsDemo.java: Some input files use unchecked or unsafe operations.
[INFO] /D:/javafx-d3/javafx-d3-demo/src/main/java/com/github/javafxd3/demo/client/democases/svg/brush/BrushTransitionsDemo.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ javafx-d3-demo ---
[INFO] Not copying test resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ javafx-d3-demo ---
[INFO] Not compiling test sources
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ javafx-d3-demo ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (default) @ javafx-d3-demo ---
[WARNING] Parameter tasks is deprecated, use target instead
[INFO] Executing tasks

main:
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ javafx-d3-demo ---
[INFO] Building jar: D:\javafx-d3\javafx-d3-demo\target\javafx-d3-demo-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ javafx-d3-demo ---
[INFO] Installing D:\javafx-d3\javafx-d3-demo\target\javafx-d3-demo-0.0.1-SNAPSHOT.jar to C:\Users\eis\.m2\repository\javafx-d3-demo\javafx-d3-demo\0.0.1-SNAPSHOT\javafx-d3-demo-0.0.1-SNAPSHOT.jar
[INFO] Installing D:\javafx-d3\javafx-d3-demo\pom.xml to C:\Users\eis\.m2\repository\javafx-d3-demo\javafx-d3-demo\0.0.1-SNAPSHOT\javafx-d3-demo-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.751 s
[INFO] Finished at: 2015-10-15T20:57:56+02:00
[INFO] Final Memory: 21M/204M
[INFO] ------------------------------------------------------------------------

**Comment by wbuchanan** [comment]
That worked for me.  There were a few exceptions thrown when I was trying out some of the demos, but seems to be a pretty awesome concept and starting point.

**Comment by stefaneidelloth** [comment]
Some more demos are working now.
