### ISSUE TITLE
Example On ClusterDendogram

### ISSUE THREAD

**Issue by SakibFarhad** [stefaneidelloth/javafx-d3#10]
Can you please Provide a small example on how to use ClusterDendogram. Having a hard time using it.

**Comment by stefaneidelloth** [comment]
The demo suite includes following example:

https://github.com/stefaneidelloth/javafx-d3/blob/master/javafx-d3-demo/src/main/java/org/treez/javafxd3/d3/democases/layout/ClusterDendogram.java

Does that work for you?
