### ISSUE TITLE
which click the "Add Point" button on the line graph about 20 times the edges will disappear. 

### ISSUE THREAD

**Issue by NickTullos** [stefaneidelloth/javafx-d3#4]
Any idea whats going on with this problem?

Thanks
Nick
![image](https://cloud.githubusercontent.com/assets/942805/21406831/2cc28778-c793-11e6-96b0-934acabf36b8.png)

**Comment by stefaneidelloth** [comment]
Could not reproduce this. 

* Do you get any error messages in the console?

* Could you please inspect the html/svg structure (In the lower Firebug  window click "HTML" and expand the html  nodes) and see if the edges/lines still exist?

**Comment by stefaneidelloth** [comment]
In regard to the performance and stability of the WebView following SO questions might be of interest:

http://stackoverflow.com/questions/10762979/performance-of-webview-in-javafx
http://stackoverflow.com/questions/41488110/java-api-for-manipulating-html-javascript-dom-elements
