### ISSUE TITLE
Capture Image after D3 render?

### ISSUE THREAD

**Issue by Setix** [stefaneidelloth/javafx-d3#7]
I'm trying to programmatically capture an image of the D3 visualization after render. It seems like there is no event that is fired after the Platform.runLater in the callback. Is there anyway to detect when the visualization is rendered?

Thanks

**Comment by stefaneidelloth** [comment]
Hi Setix,

it's hard for me to understand your request without some code example. Nevertheless I'll try to help:

A. How to save content as svg file
* I fixed the svg save feature. In the demo you can double click on the browser window 
and you will be asked for a file path to save some *.svg file that can be opened with Inkscape.
* I added two methods to the D3 class: saveSvg() and saveSvg(String filepath) to be able to trigger the save action programmatically. See end of JavaFxD3SingleDemo for an example.

B. How to wait for loading of html content with WebEngine 
If you use the JavaFx WebEngine directly to load some html content you have to wait until loading is finished. Have a look on the method "registerLoadingFinishedHook" in JavaFxD3Browser for an example. 

C. How to wait for the end of d3 transitions
If you use d3 animations/transitions you might have to wait until the svg is in a steady state before exporting it. This might help: http://stackoverflow.com/questions/10692100/invoke-a-callback-at-the-end-of-a-transition

D. Some info about JavaScript threading:
http://stackoverflow.com/questions/21718774/how-is-javascript-single-threaded
http://stackoverflow.com/questions/2734025/is-javascript-guaranteed-to-be-single-threaded
http://stackoverflow.com/questions/20225264/understanding-the-javafx-webview-threading-model

If that does not help please provide some code example.

Best regards,

Stefan
